### ISSUE TITLE
file not found, always

### ISSUE THREAD

**Issue by AnnaVd** [ge-ne/bibtool#87]
Just installed Bibtool version 2.67 via my package manager. 
So far any bibtool command gives me the same error 
```
$ bibtool references.bib
*** BibTool WARNING: File references.bib not found.
```
Did I do something wrong in during the installation maybe ? I just ran ```sudo apt install bibtool``` in Ubuntu 20.04 LTS.

**Comment by ge-ne** [comment]
You can use bibtool -h and check the line "Library path" to see where the bib files are sought.
I guess that you just havn't put the bib file is a proper place or that you are in the wrong directory when invoking bibtool.
Without any further infos I can't tell you more...

**Comment by gfcas** [comment]
In dealii/publication-list#479, I have encountered a similar problem. Below is a minimal example that runs on a GitLab runner for me. The command ``bibtool publications-1998.bib`` throws the similar error as above ``*** BibTool WARNING: File publications-1998.bib not found.``, while the version with ``./`` works fine.

```
bibtool:
  stage: check

  image: ubuntu:jammy

  script:
    - apt-get update
    - apt-get install -y bibtool git ca-certificates --no-install-recommends
    - git clone https://github.com/dealii/publication-list.git
    - cd publication-list
    - bibtool publications-1998.bib
    - bibtool ./publications-1999.bib
```
